services:
  api:
    image: api:prod
    env_file:
      - ./envs/shared_mcp.env
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8000/docs
      interval: 30s
      timeout: 10s
      retries: 3

  mcp:
    image: mcp:prod
    env_file:
      - ./envs/shared_mcp.env
    restart: unless-stopped

  nginx:
    image: nginx:1.26.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost/docs
      interval: 30s
      timeout: 10s
      retries: 3
